### ISSUE TITLE
got a error 

### ISSUE THREAD

**Issue by ETERNAL-VENOM** [noob-hackers/autoig#1]
![7dfe85b1-cefb-4251-9b56-2318ba821a12](https://user-images.githubusercontent.com/67844299/101904117-5da67a00-3bdb-11eb-8ac4-a35e3b7f96f7.jpg)

**Comment by noob-hackers** [comment]
Scrn shot please

**Comment by ETERNAL-VENOM** [comment]
uploaded bro

**Comment by noob-hackers** [comment]
Please password sahibdaalo
