### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by debjyotirana** [noob-hackers/autoig#2]
[+] Press Ctrl + C to stop Script
^[OP[+] Sending Request to Server 12331195 ...

 [!] Error

      [USE SAVED COOKIES TO SOLVE THIS ERROR]                         [OPEN AN ISSUE WITH SCREEN SHOT I WILL FIX IT ASAP]
$

**Comment by Mr-Potter-Hack** [comment]
Login issue either wrong password or username or 2FA enabled.
i also tries to login while 2FA was on.
