### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by saurabhkumaaar** [noob-hackers/autoig#4]
![Screenshot_2020-12-11-21-40-26-945_com termux](https://user-images.githubusercontent.com/75851495/101926896-cef52580-3bf9-11eb-9389-fc38e8e56d03.jpg)

**Comment by noob-hackers** [comment]
Setup run karlete ....video dekho poori

**Comment by saurabhkumaaar** [comment]
Video removed hai sir

**Comment by noob-hackers** [comment]
https://youtu.be/xsew3gr5V9Q

**Comment by saurabhkumaaar** [comment]
![Screenshot_2020-12-13-10-02-12-982_com termux](https://user-images.githubusercontent.com/75851495/102003217-58a41080-3d2a-11eb-9260-3f10d37e52c7.jpg)
Again i am getting the same error i uninstalled it and installed again this git

**Comment by noob-hackers** [comment]
Bhi setup use kar

**Comment by saurabhkumaaar** [comment]
Setup hi use kar rhe hm

**Comment by saurabhkumaaar** [comment]
bash setup 

Uske baad increase followers

Then login credentials

**Comment by noob-hackers** [comment]
O bhi setup hi use nai kiya tune

**Comment by saurabhkumaaar** [comment]
Ab kaise karu use....


Bash setup kar to rhe

**Comment by saurabhkumaaar** [comment]
Sorry bash autoig

**Comment by noob-hackers** [comment]
Video dekha bhi tumne

**Comment by saurabhkumaaar** [comment]
Haan pura last tk dekhe

**Comment by saurabhkumaaar** [comment]
Setup nhi aa rha mere me

**Comment by saurabhkumaaar** [comment]
Dir ke andar setup nhi dikh rha

**Comment by saurabhkumaaar** [comment]
![Screenshot_2020-12-13-10-36-15-692_com termux](https://user-images.githubusercontent.com/75851495/102003576-0dd8c780-3d2f-11eb-9db2-e651171e2af2.jpg)

**Comment by saurabhkumaaar** [comment]
![Screenshot_2020-12-13-17-32-51-437_com termux](https://user-images.githubusercontent.com/75851495/102011320-5f9e4380-3d69-11eb-9dfc-053f69995d07.jpg)

**Comment by saurabhkumaaar** [comment]
Why this error is coming ?
